version: "3.9"

services:
  server:
    build: ./server
    image: sarang3333/craftdex-client2.0
    container_name: server-app
    ports:
      - "3000:3000"
    networks:
      - fullstack-net
    restart: unless-stopped

  client:
    build: ./client
    image: sarang3333/craftdex-server2.0
    container_name: react-app
    ports:
      - "4000:4000"
    networks:
      - fullstack-net
    depends_on:
      - server
    restart: unless-stopped

networks:
  fullstack-net:
    driver: bridge